typedef struct {
    uint16_t bytes_per_sector;
    uint8_t sectors_per_cluster;
    uint16_t num_reserved_sectors;
    uint8_t num_fats;
    uint16_t max_root_directory_entries;
    uint16_t num_sectors;
    uint8_t media_descriptor;
    uint16_t sectors_per_fat;
    uint16_t sectors_per_track;
    uint16_t num_heads;
    uint32_t num_hidden_sectors;
    uint32_t total_logical_sectors_large;
    uint8_t physical_drive_no;
    uint8_t reserved;
    uint8_t extended_boot_signature;
    uint32_t volume_id;
    char partition_volume_label[11];
    char file_system_type[8];
} __attribute__((packed)) BiosParameterBlock;
